### ISSUE TITLE
Error when opening the extension

### ISSUE THREAD

**Issue by jimrae** [fmendes/dependencygraphforsf#2]
**Describe the bug**
When I select "Dependency graph for Apex Classes" from the command palette, I get this error:

![image](https://user-images.githubusercontent.com/1036171/163717858-4f65344a-098c-4f17-a871-1d3c90b9f70d.png)

**To Reproduce**
1. Go to VS Code
2. Open project with source retrieved
3. Press "Cmd/Shift/P" (on Mac)
4. Select "Dependency graph for Apex Classes" from the menu of options
5. See error

**Expected behavior**
Expect to see the graph rendered as shown in the readme.

**Screenshots**
![image](https://user-images.githubusercontent.com/1036171/163717858-4f65344a-098c-4f17-a871-1d3c90b9f70d.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.1
 - VSCode: 1.66.2 (Universal)
 - DependencyGraphForSF: 1.0.1 (release 4/1/2022)

Any Suggestions? Looks like a great utility, looking forward to being able to try it out.

**Comment by fmendes** [comment]
Thank you for taking the time to report the issue, @Jimrae!

The error "cannot find module 'open' " seems to indicate that the Node.js "open" library was not installed with the extension for some reason. That library invokes your default browser with the HTML file containing the dependency graph.

Would it be possible to copy/paste the rest of the error message? I see a scroll bar on the screenshot.

As a workaround, you might see that the extension created the file "dependencyGraph.html" in the project folder when you ran the "Dependency graph for Apex Classes" command. 
It contains the graph and you can open it in any browser.

I will try to reproduce the issue and, if possible, replace that "open" Node.js library.

**Comment by jimrae** [comment]
Here is the full message text:
Command 'Dependency graph for Apex Classes' resulted in an error (Cannot find module 'open'
Require stack:
- /Users/jimrae/.vscode/extensions/fernandofernandez.dependencygraphforsf-1.0.1/src/dependencyGraph.js
- /Users/jimrae/.vscode/extensions/fernandofernandez.dependencygraphforsf-1.0.1/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js)

I am running this from VS Code directly.

**Comment by jimrae** [comment]
One other note, I do see the HTML with the graph. So, like you said, appears the issue was opening the browser to view the HTML file.

**Comment by fmendes** [comment]
@jimrae I've published a new version that doesn't use that "open" package and uses VSCode standard library. It tested ok in my installation.

In order to upgrade to the new version, you will have to open the Extensions tab (Shift Command X) in VSCode then search for "DependencyGraphForSF" again, and it will show the new version 1.0.2 to install.

**Comment by jimrae** [comment]
@fmendes did anything else change? I installed the new version, and, it does open a page in the browser. However, it opens with only one box with the message "Maximum text size in diagram exceeded". whereas, with the previous version, while it wouldn't open, if I selected the HTML file that was generated (as you instructed) and opened it manually, it opened and showed the graph.  And, nothing in the repo has changed.

**Comment by fmendes** [comment]
That message "Maximum text size in diagram exceeded" appears when there are too many elements in the diagram for the mermaid.js package to display.
I believe the limit varies from 299 to 380 dependencies, depending on what else is displayed.

I will see what else might have changed and how to remedy that limit.

**Comment by jimrae** [comment]
Thank you, I think this is a great utility. Not sure how the parsing engine works, but I would offer two suggestions to address the size limit issue (since it is actually related to the charting engine). 1 would be, an option to exclude unrelated nodes. The other would be to allow selection of a "driver" node and only return items that are related to that node (parent or children). 
One use case I can see is documenting a complex LWC component stack, such as a "container" with all of its children.

**Comment by fmendes** [comment]
Thank you for your patience and excellent suggestions, @jimrae !

I've released version 1.0.3 with some of your suggestions:

- it can now handle more dependencies
- has context menus:  you can right click a class to display dependencies (parent or children) only for that class (or page, lwc, etc)
- you can right click a folder to display dependencies related to that folder (triggers, classes, pages, etc... folders)
<img width="492" alt="Screen Shot 2022-04-19 at 4 44 00 PM" src="https://user-images.githubusercontent.com/1151342/164106934-3689cc94-59ef-4ae8-a562-4cc255fd4731.png">
<img width="1169" alt="Screen Shot 2022-04-19 at 4 45 18 PM" src="https://user-images.githubusercontent.com/1151342/164107144-237b2c53-9664-41f9-80ea-164395a518c1.png">

**Comment by jimrae** [comment]
I installed 1.0.3, when I try to generate the lwc graph now (the same one that had the size issue, I get this:
![image](https://user-images.githubusercontent.com/1036171/164277010-b141487a-9837-415a-aaa3-e28bc9298c69.png)

That occurs when I run from the command Palette, or use the right-click menu on a single LWC component, or the folder level context menu.

**Comment by jimrae** [comment]
Quick update, I tried loading my chart into the mermaid.live live editor, and the error appears to be related to to some "color" lines.  This fails:
`IORetailDealerMonthlyAfter-TRIGGER(IORetailDealerMonthlyAfter TRIGGER) --> DealerScorecardHelper-CLASS(DealerScorecardHelper CLASS<br><br>STANDARD,'FireBrick');
			colors<br>BRONZE,'#cd7f32');
			colors<br>insertDealerScorecard<br>insertDealerGroupScorecard)
IORetailDealerMonthlyAfter-TRIGGER(IORetailDealerMonthlyAfter TRIGGER) --> IODealerScorecardHelper-CLASS(IODealerScorecardHelper CLASS<br><br>BRONZE,'#cd7f32');`

But this renders:
`IORetailDealerMonthlyAfter-TRIGGER(IORetailDealerMonthlyAfter TRIGGER) --> DealerScorecardHelper-CLASS(DealerScorecardHelper CLASS<br><br>STANDARD,'FireBrick');
IORetailDealerMonthlyAfter-TRIGGER(IORetailDealerMonthlyAfter TRIGGER) --> IODealerScorecardHelper-CLASS(IODealerScorecardHelper CLASS<br><br>BRONZE,'#cd7f32');`

**Comment by jimrae** [comment]
Also looks like the CLASS definitions are generating a javascript syntax error.

**Comment by fmendes** [comment]
Thank you, @jimrae !

The part that says "STANDARD,'FireBrick'); colors" and "BRONZE,'#cd7f32'); colors" shouldn't be there.
That looks like some method parameter was misinterpreted as the method name, so I will need to adjust the parsing code to account for that variation.

Would it be possible to describe the line in the DealerScorecardHelper that ends in "STANDARD,'FireBrick'); colors" ?

**Comment by jimrae** [comment]
Here are the lines in the dependencyGraph.html that is generated surrounding what you are looking for:

`IOSeasonalRateTrigger-TRIGGER(IOSeasonalRateTrigger TRIGGER) --> SeasonalRateHelper-CLASS(SeasonalRateHelper CLASS<br><br>validateMonthUniqueness<br>createMonthlyRateRecords)
RetailDealerGroupMonthlyAfter-TRIGGER(RetailDealerGroupMonthlyAfter TRIGGER) --> DealerScorecardHelper-CLASS(DealerScorecardHelper CLASS<br><br>STANDARD,'FireBrick');
			colors<br>BRONZE,'#cd7f32');
			colors<br>insertDealerScorecard<br>insertDealerGroupScorecard)
RetailDealerGroupMonthlyAfter-TRIGGER(RetailDealerGroupMonthlyAfter TRIGGER) --> PGSHelper-CLASS(PGSHelper CLASS<br><br>updateGroupPGS<br>updatePGS)`

And, there is a method in the DealerScorecardController to set some properties on the DealerScorecardHelper, that looks like this:

`public static void mapColors(){
		if(colors == null){
			colors = new Map<String,string>();
			colors.put(DealerScorecardHelper.STANDARD,'FireBrick');
			colors.put(DealerScorecardHelper.SILVER,'IndianRed');
			colors.put(DealerScorecardHelper.GOLD,'GoldenRod');
			colors.put(DealerScorecardHelper.PLATINUM,'LightGreen');
			colors.put(DealerScorecardHelper.PLATINUMP,'LimeGreen');
		}
	}`

And the properties in the DealerScoreCardHelper are defined like this:
`	public static String STANDARD='Standard';
	public static String SILVER='Silver';
	public static String GOLD='Gold';
	public static String PLATINUM='Platinum';
	public static String PLATINUMP='Platinum Plus';
`
Similarily, there is an IODealerScorecardController that has a similar mapColors function that looks like this:
`private static void mapColors(){
		if (colors == null) {
			colors = new Map<String,string>();
			colors.put(IODealerScorecardHelper.BRONZE,'#cd7f32');
			colors.put(IODealerScorecardHelper.SILVER,'Silver');
			colors.put(IODealerScorecardHelper.GOLD,'Gold');
			colors.put(IODealerScorecardHelper.PLATINUM,'LightGreen');
			colors.put(IODealerScorecardHelper.PLATINUMPLUS,'LimeGreen');
		}`


Hope that helps.

**Comment by fmendes** [comment]
Thank you, @jimrae !
I've released another version to address those issues.

**Comment by jimrae** [comment]
@fmendes Works Great, all of my use cases work without error. Thank you so much for this, it is a great utility.

**Comment by fmendes** [comment]
Awesome, @jimrae ! Thank you very much for the tests and follow up!
