### ISSUE TITLE
Dependency Graph: No Classes dependencies found in project folder 

### ISSUE THREAD

**Issue by Rohit496** [fmendes/dependencygraphforsf#3]
But I have Apex classes and LWC component when I am trying to find the dependencies I got the errors

![image](https://user-images.githubusercontent.com/73574366/209165669-9fa3753c-9d91-4fbd-b3ad-6b533ed7e7cf.png)

**Comment by Fernando-Fernandez** [comment]
Thank you, Rohit!
Could you give more details?
For example, a screenshot of your project folder structure showing that there are classes and LWCs.
It would be even better if you could zip the folders and attach it so I could have a look and debug the tool with it.
This tool only works after you download the class/LWC metadata from Salesforce.

**Comment by Rohit496** [comment]
Thanks for the reply @Fernando-Fernandez 
please find the my repo URL here https://github.com/Rohit496/Apex-Dev

**Comment by Fernando-Fernandez** [comment]
Thank you, Rohit!

I've downloaded the repo and right clicked on the classes, lwc and pages folders and it did work.
I had to reload VSCode to update it and it did take a while to activate the extensions.
It is taking longer to activate the extensions than before.

Here is what I see:
<img width="1493" alt="SCR-20221223-1ll" src="https://user-images.githubusercontent.com/19373920/209289385-0325e825-8374-415f-903e-8c9459f636f2.png">

<img width="809" alt="SCR-20221223-1lr" src="https://user-images.githubusercontent.com/19373920/209289420-5c521778-753d-49f8-ad36-da79e825ce93.png">

<img width="812" alt="SCR-20221223-1la" src="https://user-images.githubusercontent.com/19373920/209289411-3c505f0e-b1d4-44cf-8070-a1a95ddeda8e.png">

**Comment by Rohit496** [comment]
That's fine but in my case I did not get it the same output as you got 
please find my video : https://github.com/Rohit496/Apex-Dev/blob/master/My%20Video.mp4

Please give me the solution for that so I can test this extension from my side.

**Comment by fmendes** [comment]
A new version of the extension has been published. You will have to refresh extensions, update and reload it in your VSCode.
